-- Generated from MySQL "pet_vet_system".
-- Target: PostgreSQL 17 (Supabase).
--
-- Notes
--   * DATETIME / TIMESTAMP -> timestamp (no tz) on purpose: MySQL stores no tz and
--     mysql2 hands the wall-clock literal straight to node. timestamptz would
--     shift every stored value by the server offset.
--   * tinyint(1) -> smallint, not boolean: the app filters on "active = 1" /
--     "is_lost = 1" with integer literals and reads the value as a number.
--   * enum -> text + CHECK: same allowed values, easy to extend later.
--   * COLLATE "ci" reproduces utf8mb4_general_ci so UNIQUE constraints and
--     WHERE matches stay case-insensitive.
--   * FKs are added in a second pass so table order / cycles don't matter.

CREATE COLLATION IF NOT EXISTS "ci" (provider = icu, locale = 'und-u-ks-level2', deterministic = false);


-- ===================== TABLES =====================
CREATE TABLE "announcements" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(150) COLLATE "ci" NOT NULL,
  "message" text COLLATE "ci" NOT NULL,
  "image" varchar(255) COLLATE "ci",
  "audience" text COLLATE "ci" DEFAULT 'All',
  "scheduled_at" timestamp,
  "is_sent" smallint DEFAULT 0,
  "sent_at" timestamp,
  "created_by" integer,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "announcements_audience_check" CHECK ("audience" IN ('All', 'Owner', 'Staff', 'Veterinarian', 'Admin'))
);

CREATE TABLE "audit_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer,
  "staff_name" varchar(150) COLLATE "ci",
  "action" varchar(50) COLLATE "ci" NOT NULL,
  "entity_type" varchar(100) COLLATE "ci" NOT NULL,
  "entity_id" integer,
  "old_value" text COLLATE "ci",
  "new_value" text COLLATE "ci",
  "ip_address" varchar(45) COLLATE "ci",
  "user_agent" text COLLATE "ci",
  "description" text COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "breeds" (
  "id" integer NOT NULL,
  "species_id" integer NOT NULL,
  "breed_name" varchar(100) COLLATE "ci" NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "catalog_products" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category" varchar(60) COLLATE "ci" NOT NULL,
  "product_name" varchar(150) COLLATE "ci" NOT NULL,
  "species" text COLLATE "ci" DEFAULT 'General',
  "unit" varchar(60) COLLATE "ci",
  "subcategory" varchar(150) COLLATE "ci",
  "price" numeric(10,2) NOT NULL DEFAULT 0.00,
  "active" smallint NOT NULL DEFAULT 1,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "medicine_id" integer,
  PRIMARY KEY ("id"),
  CONSTRAINT "catalog_products_species_check" CHECK ("species" IN ('Dog', 'Cat', 'General'))
);

CREATE TABLE "clinic_queue" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_id" integer NOT NULL,
  "batch_id" integer,
  "status" text COLLATE "ci" NOT NULL DEFAULT 'Waiting',
  "notes" varchar(500) COLLATE "ci",
  "checked_in_by" integer NOT NULL,
  "veterinarian_id" integer,
  "checked_in_at" timestamp NOT NULL DEFAULT now(),
  "started_at" timestamp,
  "completed_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_clinic_queue_batch_pet" UNIQUE ("batch_id", "pet_id"),
  CONSTRAINT "clinic_queue_status_check" CHECK ("status" IN ('Waiting', 'In Consultation', 'Completed', 'Cancelled'))
);

CREATE TABLE "condition_regimens" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(120) COLLATE "ci" NOT NULL,
  "complaint" varchar(255) COLLATE "ci",
  "diagnosis" varchar(255) COLLATE "ci",
  "treatment" varchar(255) COLLATE "ci",
  "sort_order" integer NOT NULL DEFAULT 0,
  "active" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "name" UNIQUE ("name")
);

CREATE TABLE "condition_regimen_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "regimen_id" integer NOT NULL,
  "medicine_id" integer NOT NULL,
  "dosage" varchar(100) COLLATE "ci",
  "frequency" varchar(100) COLLATE "ci",
  "duration" varchar(100) COLLATE "ci",
  "instructions" varchar(255) COLLATE "ci",
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "regimen_medicine" UNIQUE ("regimen_id", "medicine_id")
);

CREATE TABLE "consultation_batches" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_token" varchar(100) COLLATE "ci" NOT NULL,
  "created_by" integer NOT NULL,
  "status" text COLLATE "ci" NOT NULL DEFAULT 'Active',
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_consultation_batches_token" UNIQUE ("batch_token"),
  CONSTRAINT "consultation_batches_status_check" CHECK ("status" IN ('Active', 'Completed', 'Cancelled'))
);

CREATE TABLE "consultation_charges" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consultation_id" integer NOT NULL,
  "catalog_product_id" integer NOT NULL,
  "description" varchar(255) COLLATE "ci" NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "unit_price" numeric(10,2) NOT NULL,
  "line_total" numeric(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "consultation_records" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_id" integer NOT NULL,
  "queue_id" integer,
  "complaint" varchar(255) COLLATE "ci",
  "diagnosis" text COLLATE "ci",
  "treatment_plan" text COLLATE "ci",
  "consultation_date" date,
  "follow_up_date" date,
  "vet_id" integer,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_consultation_queue_id" UNIQUE ("queue_id")
);

CREATE TABLE "draft_registrations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_owner_id" integer NOT NULL,
  "temp_reg_info" text COLLATE "ci",
  "device_id" varchar(100) COLLATE "ci",
  "payload" text COLLATE "ci",
  "sync_state" text COLLATE "ci" DEFAULT 'Draft',
  "sync_date" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "draft_registrations_sync_state_check" CHECK ("sync_state" IN ('Draft', 'Pending Sync', 'Synced'))
);

CREATE TABLE "medicines" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "medicine_name" varchar(150) COLLATE "ci" NOT NULL,
  "description" varchar(255) COLLATE "ci",
  "category" varchar(60) COLLATE "ci",
  "default_dosage" varchar(100) COLLATE "ci",
  "default_frequency" varchar(100) COLLATE "ci",
  "default_duration" varchar(100) COLLATE "ci",
  "default_instructions" varchar(255) COLLATE "ci",
  PRIMARY KEY ("id")
);

CREATE TABLE "mobile_scan_sessions" (
  "session_id" varchar(64) COLLATE "ci" NOT NULL,
  "pet_data" text COLLATE "ci" NOT NULL,
  "scan_mode" varchar(20) COLLATE "ci" DEFAULT 'single',
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("session_id")
);

CREATE TABLE "notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "title" varchar(150) COLLATE "ci" NOT NULL,
  "message" text COLLATE "ci" NOT NULL,
  "type" text COLLATE "ci" NOT NULL DEFAULT 'System',
  "link" varchar(255) COLLATE "ci",
  "is_read" smallint DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "notifications_type_check" CHECK ("type" IN ('Vaccination', 'Payment', 'QR', 'LostPet', 'System', 'Announcement', 'Record', 'Registration', 'ClinicQueue'))
);

CREATE TABLE "official_receipts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_owner_id" integer NOT NULL,
  "or_number" varchar(100) COLLATE "ci" NOT NULL,
  "total_amount" numeric(10,2) DEFAULT 0.00,
  "or_photo_path" varchar(500) COLLATE "ci",
  "payment_date" date,
  "status" text COLLATE "ci" DEFAULT 'Pending',
  "created_at" timestamp NOT NULL DEFAULT now(),
  "ocr_text" text COLLATE "ci",
  "ocr_confidence" numeric(5,2),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_or_number" UNIQUE ("or_number"),
  CONSTRAINT "official_receipts_status_check" CHECK ("status" IN ('Pending', 'Partially Verified', 'Verified'))
);

CREATE TABLE "outreach_programs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "program_name" varchar(150) COLLATE "ci" NOT NULL,
  "event_date" date,
  "end_date" date,
  "barangay" varchar(100) COLLATE "ci",
  "venue" varchar(255) COLLATE "ci",
  "notes" text COLLATE "ci",
  "status" text COLLATE "ci" NOT NULL DEFAULT 'Setup',
  "qr_token" varchar(64) COLLATE "ci",
  "qr_image_path" varchar(500) COLLATE "ci",
  "created_by" integer,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_outreach_program_qr" UNIQUE ("qr_token"),
  CONSTRAINT "outreach_programs_status_check" CHECK ("status" IN ('Setup', 'Ongoing', 'Completed', 'Cancelled'))
);

CREATE TABLE "outreach_program_services" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outreach_id" integer NOT NULL,
  "service_name" varchar(150) COLLATE "ci" NOT NULL,
  "amount" numeric(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY ("id")
);

CREATE TABLE "outreach_transactions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "outreach_id" integer NOT NULL,
  "qr_token" varchar(255) COLLATE "ci" NOT NULL,
  "qr_image_path" varchar(500) COLLATE "ci",
  "pet_owner_id" integer,
  "pet_id" integer,
  "owner_name" varchar(150) COLLATE "ci",
  "owner_contact" varchar(50) COLLATE "ci",
  "pet_name" varchar(100) COLLATE "ci",
  "barangay" varchar(100) COLLATE "ci",
  "service_date" date,
  "service_time" time,
  "total_amount" numeric(10,2) NOT NULL DEFAULT 0.00,
  "status" text COLLATE "ci" NOT NULL DEFAULT 'Pending',
  "submitted_at" timestamp,
  "verified_at" timestamp,
  "verified_by" integer,
  "rejection_reason" varchar(500) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_outreach_qr_token" UNIQUE ("qr_token"),
  CONSTRAINT "outreach_transactions_status_check" CHECK ("status" IN ('Pending', 'Submitted', 'Verified', 'Rejected'))
);

CREATE TABLE "outreach_transaction_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "transaction_id" integer NOT NULL,
  "service_name" varchar(150) COLLATE "ci" NOT NULL,
  "amount" numeric(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY ("id")
);

CREATE TABLE "owner_locations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_owner_id" integer NOT NULL,
  "latitude" numeric(10,7) NOT NULL,
  "longitude" numeric(10,7) NOT NULL,
  "accuracy_meters" numeric(10,2),
  "status" text COLLATE "ci" NOT NULL DEFAULT 'active',
  "recorded_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "owner_locations_status_check" CHECK ("status" IN ('active', 'inactive'))
);

CREATE TABLE "password_reset_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "email" varchar(255) COLLATE "ci" NOT NULL,
  "status" text COLLATE "ci" NOT NULL DEFAULT 'pending',
  "approved_by" integer,
  "approved_at" timestamp,
  "denied_by" integer,
  "denied_at" timestamp,
  "decline_reason" varchar(255) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "password_reset_requests_status_check" CHECK ("status" IN ('pending', 'approved', 'denied'))
);

CREATE TABLE "payments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_owner_id" integer NOT NULL,
  "pet_id" integer NOT NULL,
  "payment_type_id" integer NOT NULL,
  "or_id" integer,
  "or_number" varchar(100) COLLATE "ci",
  "amount" numeric(10,2),
  "payment_date" date,
  "payment_status" text COLLATE "ci" DEFAULT 'Pending',
  "validation_status" text COLLATE "ci" DEFAULT 'Pending Verification',
  "created_at" timestamp NOT NULL DEFAULT now(),
  "rejection_reason" varchar(500) COLLATE "ci",
  "reviewed_at" timestamp,
  "reviewed_by" integer,
  "qr_code_path" varchar(500) COLLATE "ci",
  PRIMARY KEY ("id"),
  CONSTRAINT "payments_payment_status_check" CHECK ("payment_status" IN ('Paid', 'Pending')),
  CONSTRAINT "payments_validation_status_check" CHECK ("validation_status" IN ('Pending Verification', 'Verified', 'Rejected'))
);

CREATE TABLE "payment_monitoring" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "or_number" varchar(100) COLLATE "ci",
  "or_amount" numeric(10,2) NOT NULL DEFAULT 0.00,
  "or_date" date,
  "or_time" time,
  "or_description" varchar(255) COLLATE "ci",
  "payment_items" text COLLATE "ci",
  "or_photo_path" varchar(500) COLLATE "ci",
  "ocr_text" text COLLATE "ci",
  "ocr_confidence" numeric(5,2),
  "pet_owner_id" integer,
  "pet_id" integer,
  "payment_type" text COLLATE "ci",
  "medicine_id" integer,
  "medicine_quantity" varchar(50) COLLATE "ci",
  "medicine_total" numeric(10,2),
  "recorded_by" integer,
  "remarks" varchar(255) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  "pm_token" varchar(64) COLLATE "ci",
  "receipt_qr_path" varchar(500) COLLATE "ci",
  "consultation_id" integer,
  "payment_reference" varchar(100) COLLATE "ci",
  "payment_status" text COLLATE "ci" NOT NULL DEFAULT 'Unpaid',
  "total_amount" numeric(10,2) NOT NULL DEFAULT 0.00,
  "consultation_date" date,
  "status_updated_by" integer,
  "status_updated_at" timestamp,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_pm_or_number" UNIQUE ("or_number"),
  CONSTRAINT "uk_pm_token" UNIQUE ("pm_token"),
  CONSTRAINT "uk_pm_consultation_id" UNIQUE ("consultation_id"),
  CONSTRAINT "uk_pm_payment_reference" UNIQUE ("payment_reference"),
  CONSTRAINT "payment_monitoring_payment_type_check" CHECK ("payment_type" IN ('Consultation', 'Vaccination', 'Medicine', 'Outreach')),
  CONSTRAINT "payment_monitoring_payment_status_check" CHECK ("payment_status" IN ('Unpaid', 'Paid', 'Cancelled'))
);

CREATE TABLE "payment_types" (
  "id" integer NOT NULL,
  "type_name" varchar(100) COLLATE "ci" NOT NULL,
  "default_amount" numeric(10,2) DEFAULT 0.00,
  PRIMARY KEY ("id")
);

CREATE TABLE "pets" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_owner_id" integer NOT NULL,
  "pet_code" varchar(50) COLLATE "ci",
  "name" varchar(100) COLLATE "ci" NOT NULL,
  "species_id" integer NOT NULL,
  "breed_id" integer,
  "breed_custom" varchar(100) COLLATE "ci",
  "sex" text COLLATE "ci" NOT NULL,
  "color" varchar(100) COLLATE "ci",
  "birthdate" date,
  "registration_date" date DEFAULT current_date,
  "status" text COLLATE "ci" DEFAULT 'Registered',
  "created_at" timestamp NOT NULL DEFAULT now(),
  "photo" varchar(255) COLLATE "ci",
  "is_lost" smallint DEFAULT 0,
  "lost_date" timestamp,
  "last_seen" varchar(255) COLLATE "ci",
  "reward" varchar(100) COLLATE "ci",
  "allergies" varchar(255) COLLATE "ci",
  "current_medication" varchar(255) COLLATE "ci",
  "important_conditions" varchar(255) COLLATE "ci",
  "special_instructions" varchar(255) COLLATE "ci",
  PRIMARY KEY ("id"),
  CONSTRAINT "pet_code" UNIQUE ("pet_code"),
  CONSTRAINT "pets_sex_check" CHECK ("sex" IN ('Male', 'Female')),
  CONSTRAINT "pets_status_check" CHECK ("status" IN ('Registered', 'Verified'))
);

CREATE TABLE "pet_owners" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "full_name" varchar(150) COLLATE "ci" NOT NULL,
  "contact_number" varchar(20) COLLATE "ci",
  "address" varchar(255) COLLATE "ci",
  "barangay" varchar(100) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  "is_payment_current" smallint DEFAULT 0,
  "emergency_contact_name" varchar(150) COLLATE "ci",
  "emergency_contact_number" varchar(30) COLLATE "ci",
  PRIMARY KEY ("id"),
  CONSTRAINT "user_id" UNIQUE ("user_id")
);

CREATE TABLE "pet_procedures" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_id" integer NOT NULL,
  "procedure_type" text COLLATE "ci" NOT NULL,
  "procedure_name" varchar(150) COLLATE "ci",
  "procedure_date" date NOT NULL,
  "veterinarian" varchar(150) COLLATE "ci",
  "result_notes" varchar(255) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "pet_procedures_procedure_type_check" CHECK ("procedure_type" IN ('Spay / Neuter', 'Surgery', 'Laboratory', 'Dental', 'Grooming', 'Other'))
);

CREATE TABLE "prescriptions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consultation_id" integer NOT NULL,
  "prescribed_date" date DEFAULT current_date,
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "prescription_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "prescription_id" integer NOT NULL,
  "medicine_id" integer NOT NULL,
  "quantity" varchar(50) COLLATE "ci",
  "dosage" varchar(100) COLLATE "ci",
  "frequency" varchar(100) COLLATE "ci",
  "duration" varchar(100) COLLATE "ci",
  "instructions" varchar(255) COLLATE "ci",
  PRIMARY KEY ("id")
);

CREATE TABLE "preventive_care_records" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_id" integer NOT NULL,
  "care_type" text COLLATE "ci" NOT NULL,
  "product_name" varchar(150) COLLATE "ci",
  "date_administered" date NOT NULL,
  "next_due_date" date,
  "administered_by" varchar(150) COLLATE "ci",
  "notes" varchar(255) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "preventive_care_records_care_type_check" CHECK ("care_type" IN ('Deworming', 'Flea / Tick Preventive', 'Heartworm Preventive', 'Other'))
);

CREATE TABLE "qr_codes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_id" integer NOT NULL,
  "qr_token" varchar(255) COLLATE "ci" NOT NULL,
  "image_path" varchar(255) COLLATE "ci",
  "issue_date" timestamp NOT NULL DEFAULT now(),
  "status" text COLLATE "ci" DEFAULT 'Pending',
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "pet_id" UNIQUE ("pet_id"),
  CONSTRAINT "qr_token" UNIQUE ("qr_token"),
  CONSTRAINT "qr_codes_status_check" CHECK ("status" IN ('Pending', 'Generated'))
);

CREATE TABLE "record_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pet_owner_id" integer NOT NULL,
  "pet_id" integer NOT NULL,
  "request_group_id" integer,
  "request_type" varchar(100) COLLATE "ci",
  "purpose" varchar(255) COLLATE "ci",
  "format" varchar(50) COLLATE "ci",
  "comments" text COLLATE "ci",
  "status" text COLLATE "ci" DEFAULT 'Pending',
  "requested_date" timestamp NOT NULL DEFAULT now(),
  "issued_date" timestamp,
  PRIMARY KEY ("id"),
  CONSTRAINT "record_requests_status_check" CHECK ("status" IN ('Pending', 'Issued'))
);

CREATE TABLE "roles" (
  "id" integer NOT NULL,
  "role_name" varchar(50) COLLATE "ci" NOT NULL
);

CREATE TABLE "species" (
  "id" integer NOT NULL,
  "species_name" varchar(100) COLLATE "ci" NOT NULL
);

CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(255) COLLATE "ci" NOT NULL,
  "password" varchar(255) COLLATE "ci",
  "role" varchar(50) COLLATE "ci" DEFAULT 'Owner',
  "status" text COLLATE "ci" DEFAULT 'active',
  "full_name" varchar(255) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  "reset_code" varchar(10) COLLATE "ci",
  "reset_code_expiry" timestamp,
  "reset_code_sent_at" timestamp,
  "reset_code_attempts" integer NOT NULL DEFAULT 0,
  "verify_code" varchar(10) COLLATE "ci",
  "verify_code_expiry" timestamp,
  "verify_sent_at" timestamp,
  "account_id" varchar(20) COLLATE "ci",
  "setup_token" varchar(64) COLLATE "ci",
  "setup_token_expiry" timestamp,
  "last_login" timestamp,
  PRIMARY KEY ("id"),
  CONSTRAINT "email" UNIQUE ("email"),
  CONSTRAINT "uk_users_account_id" UNIQUE ("account_id"),
  CONSTRAINT "users_status_check" CHECK ("status" IN ('pending', 'active', 'inactive'))
);

CREATE TABLE "vaccination_records" (
  "id" integer NOT NULL,
  "pet_id" integer NOT NULL,
  "vaccine_id" integer NOT NULL,
  "dose_no" integer,
  "dose_label" varchar(100) COLLATE "ci",
  "date_administered" date,
  "next_due_date" date,
  "status" text COLLATE "ci" DEFAULT 'Due',
  "administered_by" integer,
  "comments" varchar(255) COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "vaccination_records_status_check" CHECK ("status" IN ('Updated', 'Due', 'Overdue'))
);

CREATE TABLE "vaccines" (
  "id" integer NOT NULL,
  "vaccine_name" varchar(150) COLLATE "ci" NOT NULL,
  "species_id" integer,
  "manufacturer" varchar(150) COLLATE "ci",
  "interval_days" integer DEFAULT 365
);

CREATE TABLE "vaccine_schedules" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "vaccine_id" integer NOT NULL,
  "species_id" integer,
  "dose_no" integer NOT NULL,
  "dose_label" varchar(120) COLLATE "ci" NOT NULL,
  "interval_days" integer NOT NULL,
  "min_age_days" integer,
  "note" text COLLATE "ci",
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

-- ===================== INDEXES =====================
CREATE INDEX "fk_announcements_created_by" ON "announcements" ("created_by");
CREATE INDEX "idx_user_id" ON "audit_logs" ("user_id");
CREATE INDEX "idx_action" ON "audit_logs" ("action");
CREATE INDEX "idx_created_at" ON "audit_logs" ("created_at");
CREATE INDEX "breeds_species_id" ON "breeds" ("species_id");
CREATE INDEX "idx_catalog_category" ON "catalog_products" ("category");
CREATE INDEX "idx_catalog_active" ON "catalog_products" ("active");
CREATE INDEX "catalog_products_medicine_id" ON "catalog_products" ("medicine_id");
CREATE INDEX "clinic_queue_pet_id" ON "clinic_queue" ("pet_id");
CREATE INDEX "clinic_queue_status" ON "clinic_queue" ("status");
CREATE INDEX "clinic_queue_checked_in_by" ON "clinic_queue" ("checked_in_by");
CREATE INDEX "clinic_queue_veterinarian_id" ON "clinic_queue" ("veterinarian_id");
CREATE INDEX "clinic_queue_batch_id" ON "clinic_queue" ("batch_id");
CREATE INDEX "regimen_id" ON "condition_regimen_items" ("regimen_id");
CREATE INDEX "condition_regimen_items_medicine_id" ON "condition_regimen_items" ("medicine_id");
CREATE INDEX "consultation_batches_created_by" ON "consultation_batches" ("created_by");
CREATE INDEX "consultation_batches_status" ON "consultation_batches" ("status");
CREATE INDEX "consultation_charges_consultation_id" ON "consultation_charges" ("consultation_id");
CREATE INDEX "consultation_charges_catalog_product_id" ON "consultation_charges" ("catalog_product_id");
CREATE INDEX "consultation_records_pet_id" ON "consultation_records" ("pet_id");
CREATE INDEX "vet_id" ON "consultation_records" ("vet_id");
CREATE INDEX "draft_registrations_pet_owner_id" ON "draft_registrations" ("pet_owner_id");
CREATE INDEX "notifications_user_id" ON "notifications" ("user_id");
CREATE INDEX "official_receipts_pet_owner_id" ON "official_receipts" ("pet_owner_id");
CREATE INDEX "outreach_programs_status" ON "outreach_programs" ("status");
CREATE INDEX "event_date" ON "outreach_programs" ("event_date");
CREATE INDEX "fk_outreach_created_by" ON "outreach_programs" ("created_by");
CREATE INDEX "outreach_program_services_outreach_id" ON "outreach_program_services" ("outreach_id");
CREATE INDEX "outreach_transactions_outreach_id" ON "outreach_transactions" ("outreach_id");
CREATE INDEX "outreach_transactions_pet_owner_id" ON "outreach_transactions" ("pet_owner_id");
CREATE INDEX "outreach_transactions_pet_id" ON "outreach_transactions" ("pet_id");
CREATE INDEX "outreach_transactions_status" ON "outreach_transactions" ("status");
CREATE INDEX "barangay" ON "outreach_transactions" ("barangay");
CREATE INDEX "fk_ot_verified_by" ON "outreach_transactions" ("verified_by");
CREATE INDEX "transaction_id" ON "outreach_transaction_items" ("transaction_id");
CREATE INDEX "idx_owner_locations_owner_time" ON "owner_locations" ("pet_owner_id", "recorded_at");
CREATE INDEX "idx_user" ON "password_reset_requests" ("user_id");
CREATE INDEX "idx_status" ON "password_reset_requests" ("status");
CREATE INDEX "payments_pet_owner_id" ON "payments" ("pet_owner_id");
CREATE INDEX "payments_pet_id" ON "payments" ("pet_id");
CREATE INDEX "payment_type_id" ON "payments" ("payment_type_id");
CREATE INDEX "fk_payments_or" ON "payments" ("or_id");
CREATE INDEX "fk_payments_reviewed_by" ON "payments" ("reviewed_by");
CREATE INDEX "payment_monitoring_pet_owner_id" ON "payment_monitoring" ("pet_owner_id");
CREATE INDEX "payment_monitoring_medicine_id" ON "payment_monitoring" ("medicine_id");
CREATE INDEX "recorded_by" ON "payment_monitoring" ("recorded_by");
CREATE INDEX "idx_pm_pet" ON "payment_monitoring" ("pet_id");
CREATE INDEX "idx_pm_status" ON "payment_monitoring" ("payment_status");
CREATE INDEX "idx_pm_status_updated_by" ON "payment_monitoring" ("status_updated_by");
CREATE INDEX "pets_pet_owner_id" ON "pets" ("pet_owner_id");
CREATE INDEX "pets_species_id" ON "pets" ("species_id");
CREATE INDEX "breed_id" ON "pets" ("breed_id");
CREATE INDEX "idx_pp_pet" ON "pet_procedures" ("pet_id");
CREATE INDEX "consultation_id" ON "prescriptions" ("consultation_id");
CREATE INDEX "prescription_id" ON "prescription_items" ("prescription_id");
CREATE INDEX "prescription_items_medicine_id" ON "prescription_items" ("medicine_id");
CREATE INDEX "idx_pc_pet" ON "preventive_care_records" ("pet_id");
CREATE INDEX "record_requests_pet_owner_id" ON "record_requests" ("pet_owner_id");
CREATE INDEX "record_requests_pet_id" ON "record_requests" ("pet_id");
CREATE INDEX "idx_req_group" ON "record_requests" ("request_group_id");
CREATE INDEX "idx_vs_vaccine" ON "vaccine_schedules" ("vaccine_id");
CREATE INDEX "idx_vs_vaccine_species" ON "vaccine_schedules" ("vaccine_id", "species_id", "dose_no");

-- ===================== FOREIGN KEYS =====================
ALTER TABLE "announcements" ADD CONSTRAINT "fk_announcements_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_ibfk_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "clinic_queue" ADD CONSTRAINT "fk_clinic_queue_batch" FOREIGN KEY ("batch_id") REFERENCES "consultation_batches" ("id") ON DELETE SET NULL;
ALTER TABLE "clinic_queue" ADD CONSTRAINT "fk_clinic_queue_checked_in_by" FOREIGN KEY ("checked_in_by") REFERENCES "users" ("id");
ALTER TABLE "clinic_queue" ADD CONSTRAINT "fk_clinic_queue_pet" FOREIGN KEY ("pet_id") REFERENCES "pets" ("id") ON DELETE CASCADE;
ALTER TABLE "clinic_queue" ADD CONSTRAINT "fk_clinic_queue_veterinarian" FOREIGN KEY ("veterinarian_id") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "consultation_batches" ADD CONSTRAINT "fk_consultation_batches_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id");
ALTER TABLE "consultation_charges" ADD CONSTRAINT "fk_consultation_charges_catalog" FOREIGN KEY ("catalog_product_id") REFERENCES "catalog_products" ("id");
ALTER TABLE "consultation_charges" ADD CONSTRAINT "fk_consultation_charges_consultation" FOREIGN KEY ("consultation_id") REFERENCES "consultation_records" ("id") ON DELETE CASCADE;
ALTER TABLE "consultation_records" ADD CONSTRAINT "fk_consultation_queue" FOREIGN KEY ("queue_id") REFERENCES "clinic_queue" ("id") ON DELETE SET NULL;
ALTER TABLE "official_receipts" ADD CONSTRAINT "official_receipts_ibfk_1" FOREIGN KEY ("pet_owner_id") REFERENCES "pet_owners" ("id") ON DELETE CASCADE;
ALTER TABLE "outreach_programs" ADD CONSTRAINT "fk_outreach_created_by" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "outreach_program_services" ADD CONSTRAINT "fk_ops_outreach" FOREIGN KEY ("outreach_id") REFERENCES "outreach_programs" ("id") ON DELETE CASCADE;
ALTER TABLE "outreach_transactions" ADD CONSTRAINT "fk_ot_outreach" FOREIGN KEY ("outreach_id") REFERENCES "outreach_programs" ("id") ON DELETE CASCADE;
ALTER TABLE "outreach_transactions" ADD CONSTRAINT "fk_ot_owner" FOREIGN KEY ("pet_owner_id") REFERENCES "pet_owners" ("id") ON DELETE SET NULL;
ALTER TABLE "outreach_transactions" ADD CONSTRAINT "fk_ot_pet" FOREIGN KEY ("pet_id") REFERENCES "pets" ("id") ON DELETE SET NULL;
ALTER TABLE "outreach_transactions" ADD CONSTRAINT "fk_ot_verified_by" FOREIGN KEY ("verified_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "outreach_transaction_items" ADD CONSTRAINT "fk_oti_transaction" FOREIGN KEY ("transaction_id") REFERENCES "outreach_transactions" ("id") ON DELETE CASCADE;
ALTER TABLE "owner_locations" ADD CONSTRAINT "owner_locations_owner_fk" FOREIGN KEY ("pet_owner_id") REFERENCES "pet_owners" ("id") ON DELETE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_or" FOREIGN KEY ("or_id") REFERENCES "official_receipts" ("id") ON DELETE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "payment_monitoring" ADD CONSTRAINT "fk_pm_consultation" FOREIGN KEY ("consultation_id") REFERENCES "consultation_records" ("id") ON DELETE SET NULL;
ALTER TABLE "payment_monitoring" ADD CONSTRAINT "fk_pm_medicine" FOREIGN KEY ("medicine_id") REFERENCES "medicines" ("id") ON DELETE SET NULL;
ALTER TABLE "payment_monitoring" ADD CONSTRAINT "fk_pm_owner" FOREIGN KEY ("pet_owner_id") REFERENCES "pet_owners" ("id") ON DELETE CASCADE;
ALTER TABLE "payment_monitoring" ADD CONSTRAINT "fk_pm_pet" FOREIGN KEY ("pet_id") REFERENCES "pets" ("id") ON DELETE SET NULL;
ALTER TABLE "payment_monitoring" ADD CONSTRAINT "fk_pm_recorded_by" FOREIGN KEY ("recorded_by") REFERENCES "users" ("id");
ALTER TABLE "payment_monitoring" ADD CONSTRAINT "fk_pm_status_updated_by" FOREIGN KEY ("status_updated_by") REFERENCES "users" ("id") ON DELETE SET NULL;
ALTER TABLE "pet_procedures" ADD CONSTRAINT "fk_pp_pet" FOREIGN KEY ("pet_id") REFERENCES "pets" ("id") ON DELETE CASCADE;
ALTER TABLE "preventive_care_records" ADD CONSTRAINT "fk_pc_pet" FOREIGN KEY ("pet_id") REFERENCES "pets" ("id") ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION trg_announcements_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "announcements_updated_at_trg"
BEFORE UPDATE ON "announcements"
FOR EACH ROW EXECUTE FUNCTION trg_announcements_updated_at();

CREATE OR REPLACE FUNCTION trg_catalog_products_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "catalog_products_updated_at_trg"
BEFORE UPDATE ON "catalog_products"
FOR EACH ROW EXECUTE FUNCTION trg_catalog_products_updated_at();

CREATE OR REPLACE FUNCTION trg_clinic_queue_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "clinic_queue_updated_at_trg"
BEFORE UPDATE ON "clinic_queue"
FOR EACH ROW EXECUTE FUNCTION trg_clinic_queue_updated_at();

CREATE OR REPLACE FUNCTION trg_condition_regimens_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "condition_regimens_updated_at_trg"
BEFORE UPDATE ON "condition_regimens"
FOR EACH ROW EXECUTE FUNCTION trg_condition_regimens_updated_at();

CREATE OR REPLACE FUNCTION trg_consultation_batches_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "consultation_batches_updated_at_trg"
BEFORE UPDATE ON "consultation_batches"
FOR EACH ROW EXECUTE FUNCTION trg_consultation_batches_updated_at();

CREATE OR REPLACE FUNCTION trg_mobile_scan_sessions_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "mobile_scan_sessions_updated_at_trg"
BEFORE UPDATE ON "mobile_scan_sessions"
FOR EACH ROW EXECUTE FUNCTION trg_mobile_scan_sessions_updated_at();

CREATE OR REPLACE FUNCTION trg_password_reset_requests_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "password_reset_requests_updated_at_trg"
BEFORE UPDATE ON "password_reset_requests"
FOR EACH ROW EXECUTE FUNCTION trg_password_reset_requests_updated_at();
